### ISSUE TITLE
Fix doc generation in Github actions

### ISSUE THREAD

**Issue by chaws** [Linaro/squad-client#130]
Tests are crashing in Actions: https://github.com/Linaro/squad-client/runs/4241273565?check_suite_focus=true#step:5:65

Here's a possible fix: https://github.com/mkdocs/mkdocs/issues/2469

**Comment by jscook2345** [comment]
While trying to fix the problem, I found that one of the dependencies is the problem:

```
https://github.com/zostera/django-bootstrap3/blob/main/setup.py#L50
```

This is causing the wrong version of `importlib-metadata` to be installed.

See here: https://github.com/zostera/django-bootstrap3/issues/608

I don't think this can be fixed until the dependency fixes their `setup.py`.

**Comment by chaws** [comment]
Hum, have you tried downgrading django-bootstrap? 
Some weird thing is that I created a whole new venv but still wasn't able to reproduce this crash. Maybe that's because I'm trying on Python 3.8? I'll give it a shot at 3.6 later today

**Comment by chaws** [comment]
This error is affecting squad as well: https://github.com/Linaro/squad/runs/4252551492?check_suite_focus=true

It seems Django is not configuring jinja, and i think we should try to figure that out before

**Comment by jscook2345** [comment]
Yes, this is a `squad` regression, which is why it affects the unit tests in `squad-client`.

The important line is here:

```
'importlib-metadata<3; python_version<"3.8"',
```

This means that for python's less than 3.8, use an older `importlib-metadata`. This is why it does not fail for your 3.8 test, but fails in CI for 3.6, 3.7.

This isn't an official `django` package, and there is an issue open against it, but I don't know what the resolution will be.

**Comment by chaws** [comment]
This was fixed in SQUAD: https://github.com/Linaro/squad/commit/0a87231069a4a0fc8e75ad7d45f18a86b32859d1

It'll fix squad-client on next SQUAD release
