### ISSUE TITLE
Compare view times out

### ISSUE THREAD

**Issue by danrue** [Linaro/squad-client#56]
The following URL seems to break qa-reports.linaro.org (504 timeout followed by all qa-reports requests timing out for a minute or two):

https://qa-reports.linaro.org/_/comparetest/?project=34&project=22&project=6&project=58&project=135&project=40&project=23&project=232&project=310&suite=ltp-syscalls-tests&test=syslog07

Reducing the load a bit, even the following no longer actually loads:

https://qa-reports.linaro.org/_/comparetest/?project=232&project=310&suite=ltp-syscalls-tests&test=syslog07

I know these are big requests but I used to do them regularly and they worked fine. Any ideas?

**Comment by mwasilew** [comment]
@danrue This is know issue. It was reported around 2 weeks ago on IRC but I can't find a ticket for it in squad. We'll take a look.

**Comment by mwasilew** [comment]
@danrue this https://qa-reports.linaro.org/_/comparetest/?project=232&project=310&suite=ltp-syscalls-tests&test=syslog07 works for me, but the response happens in ~50 seconds. So it's very close to timing out. I'll keep this ticket open as I don't think we have a proper solution.

**Comment by mwasilew** [comment]
@chaws restored the database to a new VM and upgraded the verison. This has surprising effect on performance:
https://testing-qa-reports.ctt.linaro.org/_/comparetest/?project=34&project=22&project=6&project=58&project=135&project=40&project=23&project=232&project=310&suite=ltp-syscalls-tests&test=syslog07

**Comment by chaws** [comment]
@mwasilew I think we can make this page much quicker if we used SuiteMetadata id to fetch wanted tests. The slow part of the current implementation is due to not knowing in which TestRun the wanted test is. So we either join test-testrun-build or get all testrun ids to filter tests. Both of these are slow. The latter can be improved by passing small batches of testrun ids. Problem is there's still a query using test name. The same procedure is repeated by the number of projects in the compare view.

If we used SuiteMetadata, we'd get the test name using a single id. The rest of the work would be checking and fetching its environment. The same id could be used to find tests in other projects as well, making it O(1) regarding number of projects.

The only downside is that SuiteMetadata is optional in Test, so don't know how much confidence there is. Let me work on a quick PoC next week to check if that is reasonable as replacement for compare view backend implementation.

**Comment by danrue** [comment]
I clicked on the first link in this issue and it still does not work. Does it work for you @chaws ?

![image](https://user-images.githubusercontent.com/409011/88677159-8e659700-d0b2-11ea-819f-8d9cdce44d15.png)

**Comment by chaws** [comment]
hum... it's intermittent for me. I'll have another look at the queries

**Comment by chaws** [comment]
Ok, after @stevanradakovic 's change to query planner settings, we're not seeing timeouts consistently. I'll keep an eye in qa-reports and will report back here

**Comment by chaws** [comment]
It's been a week that is not timing out anymore, consistently .

@danrue please re-open this ticket if you experience time outs again.
