### ISSUE TITLE
move flake8 testing to travis ci

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad-client#74]
I'd like to move the flake8 testing done under `tests/test_code_quality.py` to a more robust ci solution in travis. Is that something you'd be interested in? We could use tox, pre-commit, or just matrix testing in travis.

I'd mainly like to avoid running `flake8` every time I run the system tests.

**Comment by mwasilew** [comment]
@jscook2345 could you give some justification? I really don't see any reasons to skip static analysis when testing.

**Comment by jscook2345** [comment]
@mwasilew 

I don't want to skip analysis, but rather push it back in the development cycle.

Ideally, tests should be fast so that they can be run continuously as you develop features or fixes. Static analysis is slow and it tests all files, not just files that have changed.

I think static analysis is best done as a pre-commit hook or done as a part of CI in travis.

What do you think?

**Comment by mwasilew** [comment]
It is part of travis job. This is where my confusion comes from. As I understand this ticket you want to remove it.

**Comment by jscook2345** [comment]
I want it to only run in Travis. Not when I run the tests on my local machine. Does that make more sense?

**Comment by mwasilew** [comment]
Yeah, just send the patch. This should be easy to do.

**Comment by chaws** [comment]
Hey @jscook2345, I don't know if you were aware of that yet (probably you are), but you can run your specific tests by

```bash
./manage.py test tests.test_submit_tuxbuild.SubmitTuxbuildCommandTest.test_submit_tuxbuild_build
```

It would still be a little slow because squad needs to be up and running before running squad-client tests.

Also flask8 takes a bit over 1s to execute

```bash
[0|0]squad_client(master) $ time flake8

real	0m0.491s
user	0m1.427s
sys	0m0.057s
```

I'm closing this one (doing an issue cleanup), but please re-open if you have a patch that moves this to travis (I don't oppose to that)
