### ISSUE TITLE
Traceback in Project.compare_builds during pipeline execution

### ISSUE THREAD

**Issue by jscook2345** [Linaro/squad-client#96]
```
Traceback (most recent call last):
  File "build_report.py", line 32, in <module>
    cb = Project.compare_builds(prev_build.id, build.id)
  File "/usr/local/lib/python3.8/site-packages/squad_client/core/models.py", line 360, in compare_builds
    return SquadApi.get(url, params).json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

See the pipeline here: https://gitlab.com/Linaro/lkft/reports/squad-report/-/jobs/889433815#L101

**Comment by chaws** [comment]
I think squad-client got a malformed json from the server. This is probably due to timeout or something else. I can make `Project.compare_builds` handle malformed json, but the real fix would be in squad. Do you happen to know which builds were used? I couldn't figure it out by looking it here https://gitlab.com/Linaro/lkft/reports/squad-report/-/blob/master/build_report.py

**Comment by jscook2345** [comment]
```
$ cat build.json | python -m json.tool
{
    "group": "lkft",
    "project": "linux-next-master",
    "build": "next-20201203",
    "prev_build": "next-20201201"
}
```

**Comment by chaws** [comment]
@jscook2345 sorry for delay! 

I re-run the same comparison and got no error. It was probably due to a timeout. I managed to make this comparison a lot quicker. It'll be available when this https://github.com/Linaro/squad/pull/946 gets merged.

I'm closing this issue for now, but please re-open if the issue persists.
